### ISSUE TITLE
`unikube system verify` prints "Versions cannot be compared" while still succeeding

### ISSUE THREAD

**Issue by tschale** [unikubehq/cli#216]
`unikube system verify` yielded following output for me:
```
[INFO] Versions cannot be compared, because of error Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/src/helpers.py", line 113, in compare_current_and_latest_versions
    current_version = pkg_resources.require("unikube")[0].version
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 7.1.2 (/home/gutschi/.local/lib/python3.8/site-packages), Requirement.parse('click==8.0.3'), {'unikube'})

[INFO] Checking Docker  Ok (Version 20.10.8)
[INFO] Checking Docker Engine  Ok
[INFO] Checking Kubectl  Ok (Version 1.22.1)
[INFO] Checking k3d  Ok (Version 4.4.7)
[INFO] Checking Telepresence  Ok (Version 2.3.7)
[SUCCESS] Local dependencies verified.
```
It seems to be based on my installed version of `click`, which is 7.1.2, but Unikube seems to expect 8.0.3. Should that be a requirement for the pip install? Should `unikube system verify` fail at this stage?

**Comment by SteinRobert** [comment]
I have seen this too, when I have activated a virtualenv. You don't happen to have another virtualenv activated, do you?

**Comment by tschale** [comment]
No, there's no virtualenv activated. But interestingly enough, today it seems to be requests:
```
[...]
pkg_resources.ContextualVersionConflict: (requests 2.20.1 (/home/gutschi/.local/lib/python3.8/site-packages), Requirement.parse('requests<2.27.0,>=2.25.1'), {'unikube'})
[...]
```
So it doesn't seem to be limited on one package.

**Comment by SteinRobert** [comment]
So there is obviously some dependency clash with already installed python packages.

I just stumbled upon this installation process for another Python based cli:
https://docs.datasette.io/en/stable/installation.html#using-pipx

Could you maybe check installing the unikube cli via pipx? If it works we could add it to our installation instructions.

**Comment by tschale** [comment]
pipx seems to solve it. I kept the existing installation, `unikube system verify` now only prints the expected info output:
![image](https://user-images.githubusercontent.com/5681839/142590613-16a09ed5-7331-4976-8424-f5b1960c267a.png)

**Comment by schwobaseggl** [comment]
@tschale  Is this resolved? Seems like a general issue that can occur with any python package in any environment.

**Comment by tschale** [comment]
@schwobaseggl Not exactly resolved, but the workaround with `pipx` works and I guess we can't fix anything here. As @SteinRobert suggested we might want to add that information in our installation instrauctions.

**Comment by schwobaseggl** [comment]
@tschale @SteinRobert A hint along the lines of  "Some package versions can collide with versions already installed on your system" or "Install into a virtualenv"?
Maybe there is a way for unikube to automatically install its dependencies into a virtualenv and use that one for the unikube command?

**Comment by SteinRobert** [comment]
Installing the cli into a virtualenv would probably not be the way to go, since one would always have to `source` exactly that virtualenv right? Somehow we would need to link the cli into the user's bin folder, or something similar.

Just had a look at the `poetry` cli. These guys have a clever [installation script](https://github.com/python-poetry/poetry/blob/master/install-poetry.py). This script can simply be `curl`ed and put into a python interpreter. If find this solution very intriguing.

**Comment by schwobaseggl** [comment]
I don't know exactly at what (meta) level poetry operates, but since we have to install our python package into some environment, we can never be fully sure that there are no conflicts. 
If a user has no knowledge about Python package management, the chance is also quite low that they have a lot of manually installed Python packages with conflicting dependencies.
On the other hand, if they do know about the intricacies of pip and the like, they should have an easy time resolving the issue. But if there is an easy way to isolate unikube from the system Python, I am all for it. Having a smart installation script and making the `unikube` command automatically pick its interpreter (from an env set during installation) should be possible. I would not make this too much of a priority.

I think we should handle the error though and translate it into a more friendly message.

**Comment by SteinRobert** [comment]
Just had a deeper look into the issue.
The exception is raised [here](https://github.com/unikubehq/cli/blob/main/src/helpers.py#L113).

I was asking myself - why even use `pkg_resources`? Seems a bit of an overkill for me. It would probably be easier to just read the `VERSION` file in the base directory of the package.
