### ISSUE TITLE
`k3d cluster create` max length for name is ignored

### ISSUE THREAD

**Issue by tschale** [unikubehq/cli#256]
We currently ignore k3ds limit of 32 characters for a clusters name:
![image](https://user-images.githubusercontent.com/5681839/148752605-153c1e18-14fa-4466-9146-b6f765c9d8c3.png)

When running `project up` for a project with a longer name, the k3d cluster won't be created and fails with following error:
```
[INFO] Setting up a Kubernetes cluster (with provider k3d) for project 'FF Automation Hub Keycloak 2'.
[INFO] Kubernetes cluster for 'FF Automation Hub Keycloak 2' does not exist, creating it now.
-[INFO] Waiting for the cluster to be ready (1/10).
-[INFO] Waiting for the cluster to be ready (2/10).
-[INFO] Waiting for the cluster to be ready (3/10).
-[INFO] Waiting for the cluster to be ready (4/10).
-[INFO] Waiting for the cluster to be ready (5/10).
/[INFO] Waiting for the cluster to be ready (6/10).
/[INFO] Waiting for the cluster to be ready (7/10).
/[INFO] Waiting for the cluster to be ready (8/10).
/[INFO] Waiting for the cluster to be ready (9/10).
/[ERROR] Something went completely wrong with the cluster spin up (or we got a timeout).
[INFO] Now connecting Telepresence daemon. You probably have to enter your 'sudo' password.
Traceback (most recent call last):
  File "/home/gutschi/.local/pipx/venvs/unikube/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/gutschi/.local/pipx/venvs/unikube/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/gutschi/.local/pipx/venvs/unikube/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

[...]
```

I've also seen a `ValueError: Project does not contain the kubeconfigPath parameter` instead of the `ConnectionRefusedError`.

Does this have implications for the frontend? Should we have a limit on the length of a projects name? Or should the cli just cut a projects slug after 32 chars?

**Comment by buschNT** [comment]
Note: Maybe we should also think about shortening the "unikube-" cluster prefix to something like "u-", "uk-", etc. . Alternatively we could also discuss using the ID as cluster name.
