### ISSUE TITLE
AttributeError: module 'kubernetes.client' has no attribute 'NetworkingV1beta1Api'

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/cli#299]
```
[INFO] Setting up a Kubernetes cluster (with provider k3d) for project 'Unikube Platform'.
[INFO] Kubernetes cluster for 'Unikube Platform' already exists, starting it now.
[INFO] Now connecting Telepresence daemon. You probably have to enter your 'sudo' password.
Traceback (most recent call last):
  File "/usr/local/bin/unikube", line 33, in <module>
    sys.exit(load_entry_point('unikube==1.2.7', 'console_scripts', 'unikube')())
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/unikube/cli/project.py", line 263, in up
    k8s = KubeAPI(provider_data)
  File "/usr/local/Cellar/unikube/1.2.7/libexec/lib/python3.8/site-packages/unikube/local/system.py", line 373, in __init__
    self._networking_api = client.NetworkingV1beta1Api(self._api_client)
AttributeError: module 'kubernetes.client' has no attribute 'NetworkingV1beta1Api'
```

**Comment by SteinRobert** [comment]
This also happens for
`unikube app update`
