### ISSUE TITLE
Deck install 404 error

### ISSUE THREAD

**Issue by martinmarsicano** [unikubehq/cli#312]
When running
`unikube deck install`

I get the following error:
![Screen Shot 2022-03-17 at 18 03 17](https://user-images.githubusercontent.com/33671308/158894774-b1ed81ac-a61f-4f4c-ab3d-c2ccf17dc1bd.png)

Although the application gets up and works
![Screen Shot 2022-03-17 at 18 05 14](https://user-images.githubusercontent.com/33671308/158895042-7cf497f0-34e6-4f18-980d-ecbe47718c5a.png)

**Comment by georgkrause** [comment]
I can reproduce this with Python 3.10 on Linux:

```
? Please select a deck buzzword-counter
[INFO] Requesting manifests. This process may take a few seconds.
[INFO] Installing Kubernetes resources to the cluster.  [####################################]  100%          
Traceback (most recent call last):
  File "/home/georg/.local/bin/unikube", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/georg/.local/lib/python3.10/site-packages/unikube/cli/deck.py", line 262, in install
    ingress_data = get_ingress_data(deck, provider_data)
  File "/home/georg/.local/lib/python3.10/site-packages/unikube/cli/deck.py", line 62, in get_ingress_data
    ingresss = KubeAPI(provider_data, deck).get_ingress()
  File "/home/georg/.local/lib/python3.10/site-packages/unikube/local/system.py", line 422, in get_ingress
    ret = self._networking_api.list_namespaced_ingress(self._namespace, watch=False)
  File "/home/georg/.local/lib/python3.10/site-packages/kubernetes/client/api/networking_v1beta1_api.py", line 1400, in list_namespaced_ingress
    return self.list_namespaced_ingress_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/home/georg/.local/lib/python3.10/site-packages/kubernetes/client/api/networking_v1beta1_api.py", line 1515, in list_namespaced_ingress_with_http_info
    return self.api_client.call_api(
  File "/home/georg/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/georg/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/georg/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/georg/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/home/georg/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e5555cb6-25fc-4469-82cf-990cdafeabe4', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ea865251-53cd-4f78-8158-0cc645536463', 'X-Kubernetes-Pf-Prioritylevel-Uid': '1f0d39ad-a055-42e4-bcc2-e0149bde902e', 'Date': 'Tue, 05 Apr 2022 07:46:58 GMT', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
```
