### ISSUE TITLE
system commands stop working after failed unikube system install

### ISSUE THREAD

**Issue by tobifroe** [unikubehq/cli#57]
I'm able to reproduce this on macOS 10.15.5, the same errors are raised after uninstalling/reinstalling the unikube package.

1. Run `unikube system install`, have it fail
![Bildschirmfoto 2021-06-22 um 10 08 03](https://user-images.githubusercontent.com/40638719/122888029-bd779d80-d341-11eb-8f5c-21e664345f35.png)
2. Run `unikube system verify`, output:
```
[INFO] Checking Homebrew  Ok (Version 2.6.2)
[INFO] Checking Docker  Ok (Version 20.10.6)
[INFO] Checking Docker Engine  Ok
[INFO] Checking Kubectl  Ok (Version 1.19.7)
[INFO] Checking k3d  Ok (Version 4.3.0)
[INFO] Checking Telepresence Traceback (most recent call last):
  File "/usr/local/bin/unikube", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/src/cli/system.py", line 73, in verify
    report_data = probe_dependencies(silent=verbose)
  File "/usr/local/lib/python3.9/site-packages/src/local/dependency.py", line 245, in probe_dependencies
    success, msg = check.probe(silent=silent)
  File "/usr/local/lib/python3.9/site-packages/src/local/dependency.py", line 50, in probe
    version, sufficient = self.check_version(cmd_version)
  File "/usr/local/lib/python3.9/site-packages/src/local/dependency.py", line 205, in check_version
    installed_major, installed_minor = map(int, self.installed_version.split(".")[0:2])
ValueError: invalid literal for int() with base 10: ''
```
3. Run `unikube system install`again, output:
```
Traceback (most recent call last):
  File "/usr/local/bin/unikube", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/src/cli/system.py", line 51, in install
    report_data = probe_dependencies(silent=True)
  File "/usr/local/lib/python3.9/site-packages/src/local/dependency.py", line 245, in probe_dependencies
    success, msg = check.probe(silent=silent)
  File "/usr/local/lib/python3.9/site-packages/src/local/dependency.py", line 50, in probe
    version, sufficient = self.check_version(cmd_version)
  File "/usr/local/lib/python3.9/site-packages/src/local/dependency.py", line 88, in check_version
    self.installed_version = semantic_version.Version(cmd_version)
  File "/usr/local/lib/python3.9/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/usr/local/lib/python3.9/site-packages/semantic_version/base.py", line 302, in parse
    raise ValueError('Invalid empty version string: %r' % version_string)
ValueError: Invalid empty version string: ''
```

**Comment by SteinRobert** [comment]
Seems like Telepresence jumped from 0.102 style releases to something like 2.1.0.

The version string output probably changed.

**Comment by Schille** [comment]
This should be solved with the `Telepresence 2` implementation.
